@startuml

Bot -> database: check_database()
    database -> downloads: download_tcg()
    downloads --> database: tcg_download

    database -> downloads: download_dl()
    downloads --> database: dl_download

    database -> downloads: download_skills()
    downloads --> database: skills_download

    database -> AsyncIOMotorClient: get_stored_md5()
    AsyncIOMotorClient --> database: stored_md5

    alt tcg_download.md5 != stored_md5.tcg
        database -> AsyncIOMotorClient: wipe_cards()
        AsyncIOMotorClient --> database
        database -> AsyncIOMotorClient: save(tcg_download.data)
        AsyncIOMotorClient --> database
        database -> database: set_tcg_md5(tcg_download.md5)
        database -> database: set_dl_md5("")
    end

    alt dl_download.md5 != stored_md5.dl
        database -> AsyncIOMotorClient: update(dl_download.data)
        AsyncIOMotorClient --> database
        database -> database: set_dl_md5(dl_download.md5)
    end

    alt skills_download.md5 != stored_md5.skills
        database -> AsyncIOMotorClient: wipe_skills()
        AsyncIOMotorClient --> database
        database -> AsyncIOMotorClient: save(skills_download.data)
        AsyncIOMotorClient --> database
        database -> database: set_skills_md5(skills_download.md5)
    end

    database -> AsyncIOMotorClient: save(stored_md5)
    AsyncIOMotorClient --> database

database --> Bot

@enduml
